/**
 * @author zz85 / http://www.lab4games.net/zz85/blog
 *
 * Two pass Gaussian blur filter (horizontal and vertical blur shaders)
 * - described in http://www.gamerendering.com/2008/10/11/gaussian-blur-filter-shader/
 *   and used in http://www.cake23.de/traveling-wavefronts-lit-up.html
 *
 * - 9 samples per pass
 * - standard deviation 2.7
 * - "h" and "v" parameters should be set to "1 / width" and "1 / height"
 */

THREE.HorizontalBlurShader = {

	uniforms: {

		"tDiffuse": { value: null },
		"h":        { value: 0.0 }, 
		"v":        { value: 0.0 }

	},

	vertexShader: [

		"varying vec2 vUv;",

		"void main() {",

			"vUv = uv;",
			"gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );",

		"}"

	].join( "\n" ),

	fragmentShader: [

		"uniform sampler2D tDiffuse;",
		"uniform float h;",
		"uniform float v;",

		"varying vec2 vUv;",
        
"// automatically generated by GenerateGaussFunctionCode in GaussianBlur.h ",
"vec4 GaussianBlur( sampler2D tex0, vec2 centreUV, vec2 halfPixelOffset, vec2 pixelOffset )   ",
"{      ",
"    vec4 colOut			= vec4(0.0); ",
"    vec2 texCoordOffset  = vec2(0.0); ",
"    vec4 col             = vec4(0.0); ",
"        texCoordOffset	=    0.66640 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.02954 * col;",
"        texCoordOffset	=    2.49848 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.03910 * col;",
"        texCoordOffset	=    4.49726 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.03844 * col;",
"        texCoordOffset	=    6.49605 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.03743 * col;",
"        texCoordOffset	=    8.49483 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.03609 * col;",
"        texCoordOffset	=    10.49362 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.03446 * col;",
"        texCoordOffset	=    12.49240 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.03259 * col;",
"        texCoordOffset	=    14.49119 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.03052 * col;",
"        texCoordOffset	=    16.48997 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.02830 * col;",
"        texCoordOffset	=    18.48876 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.02600 * col;",
"        texCoordOffset	=    20.48754 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.02365 * col;",
"        texCoordOffset	=    22.48633 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.02130 * col;",
"        texCoordOffset	=    24.48511 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.01900 * col;",
"        texCoordOffset	=    26.48390 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.01679 * col;",
"        texCoordOffset	=    28.48268 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.01469 * col;",
"        texCoordOffset	=    30.48147 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.01272 * col;",
"        texCoordOffset	=    32.48026 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.01092 * col;",
"        texCoordOffset	=    34.47904 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00928 * col;",
"        texCoordOffset	=    36.47783 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00781 * col;",
"        texCoordOffset	=    38.47662 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00651 * col;",
"        texCoordOffset	=    40.47540 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00537 * col;",
"        texCoordOffset	=    42.47419 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00439 * col;",
"        texCoordOffset	=    44.47298 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00355 * col;",
"        texCoordOffset	=    46.47176 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00285 * col;",
"        texCoordOffset	=    48.47055 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00226 * col;",
"        texCoordOffset	=    50.46934 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00178 * col;",
"        texCoordOffset	=    52.46813 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00138 * col;",
"        texCoordOffset	=    54.46692 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00107 * col;",
"        texCoordOffset	=    56.46571 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00081 * col;",
"        texCoordOffset	=    58.46450 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00062 * col;",
"        texCoordOffset	=    60.46329 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00046 * col;",
"        texCoordOffset	=    62.46208 * pixelOffset;",
"        col			    = texture2D( tex0, centreUV + texCoordOffset ) + texture2D( tex0, centreUV - texCoordOffset );",
"        colOut			+=    0.00034 * col;",
" ",
"    return colOut;   ",
"} ",


	"void main() {",
		"vec4 texel  = texture2D( tDiffuse, vUv);",
		"vec4 sonuc = GaussianBlur( tDiffuse, vUv, vec2(0.0), vec2(h, v)  );",
		"sonuc[3] = texel[3];",
		"gl_FragColor = sonuc;",
	"}"

	].join( "\n" )

};
